[project]
name = 'smart_bounty_contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stx_smart_bounty_contract]
path = 'contracts/stx_smart_bounty_contract.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
